name: 🏗 build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          # std variants with additional features
          - name: "std"
            features: "std,dsl"
            cargo-flags: ""
            additional-name: "sendable"
            additional-features: "sendable"
          - name: "std"
            features: "std,dsl"
            cargo-flags: ""
            additional-name: "std-duration"
            additional-features: "std-duration"
          - name: "std"
            features: "std,dsl"
            cargo-flags: ""
            additional-name: "web-time"
            additional-features: "web-time"
          - name: "no-std"
            features: ""
            cargo-flags: "--no-default-features"
            additional-name: "base"
            additional-features: ""

    runs-on: ubuntu-latest
    name: "build & test (${{ matrix.name }} + ${{ matrix.additional-name }})"

    steps:
    - uses: actions/checkout@v5
    
    - name: Build (${{ matrix.name }})
      run: cargo build --verbose ${{ matrix.cargo-flags }} --features="${{ matrix.features }}"
    
    - name: Test (${{ matrix.name }})
      run: cargo test --verbose --lib ${{ matrix.cargo-flags }} --features="${{ matrix.features }}"
    
    - name: Build (${{ matrix.name }} + ${{ matrix.additional-name }})
      run: |
        if [ -n "${{ matrix.additional-features }}" ]; then
          cargo build --verbose ${{ matrix.cargo-flags }} --features="${{ matrix.features }},${{ matrix.additional-features }}"
        else
          cargo build --verbose ${{ matrix.cargo-flags }} --features="${{ matrix.features }}"
        fi
    
    - name: Test (${{ matrix.name }} + ${{ matrix.additional-name }})
      run: |
        if [ -n "${{ matrix.additional-features }}" ]; then
          cargo test --verbose --lib ${{ matrix.cargo-flags }} --features="${{ matrix.features }},${{ matrix.additional-features }}"
        else
          cargo test --verbose --lib ${{ matrix.cargo-flags }} --features="${{ matrix.features }}"
        fi

  clippy:
    runs-on: ubuntu-latest
    name: "clippy checks"

    steps:
    - uses: actions/checkout@v5
    
    - name: Clippy (all targets)
      run: cargo clippy --all-targets
